### ISSUE TITLE
[MAMACPP] MamaSubscription destructor does not completely disconnect application from MamaSubscriptionImpl.

### ISSUE THREAD

**Issue by cjwmorgan-sol-sys** [OpenMAMA/OpenMAMA#114]
### OpenMAMA Version
Version: 2.3.3

###  Description:
On the openmama Developer Wiki under Bridge Documentation for myMiddlewareBridgeMamaSubscription_destroy () it states “…the destroy method adds an event to the queue to invokes the destroy callback, which notifies the client application of the successful destroy of the subscription.”

When an application destructs a MamaSubscription object, the application onDestroy is called inline, and the MamaSubscription object is freed, but the corresponding MamaSubscriptionImpl object is not freed.  So far so good – it is the MamaSubscriptionImpl object pointer that is the closure to the C-layer and this is still valid, unfreed memory.  However, at this point the MamaSubscriptionImpl object’s mCallback pointer still points to the application’s MamaSubscriptionCallback object.  The application may have freed this memory since MamaSubscriptionCallback::onDestroy() has been called.

### Example Scenario :

If we look at MamdaSubscription, it in fact does not implement MamaSubscriptionCallback::onDestroy at all.  It will always destroy the callback (MamdaSubscription::mImpl) immediately after destroying the underlying MamaSubscription.  This happens to occur after onDestroy is called since it is called inline with MamaSubscription::~MamaSubscription.  But nevertheless, it is freed immediately after onDestroy is called inline with the call to MamaSubscription::~MamaSubscription().

Now, sometime later, the C-layer onDestroy is called.  This calls the static MamaSubscription::onSubscriptionDestroy which calls MamaSubscriptionImpl::InvokeDestroy().  This checks if MamaSubscriptionImpl::mCallback is NULL (it is not – in the case of a MamdaSubscription it is still pointing to a freed MamdaSubscriptionImpl object) and tries to invoke the onDestroy() method.  If the vtable pointer is no longer valid, a core here is quite likely.

### Potential Fix :

Even if a core does not occur, the application would see onDestroy() twice – once inline with when the destroy was started and a second time when the lower layer destroy was completed.  It seems the design intent here is to decouple the MamaSubscriptionImpl from everything above it when the MamaSubscription is destroyed.  To do this, it seems the right thing to do in the C++ layer would be to set MamaSubscriptionImpl::mCallback to NULL when setting MamaSubscriptionImpl::mFreed to true (or alternatively include mFreed in the tests that check mCallback == NULL).

Here is a patch that includes mFreed the test that mCallback == NULL.

[MamaSubscription.cpp.patch.txt](https://github.com/OpenMAMA/OpenMAMA/files/112977/MamaSubscription.cpp.patch.txt)

**Comment by sbeattie84** [comment]
Yes, I think that this is a potential issue and that the attached patch is the correct fix.

It looks to me that the lack of a check for mFreed inside InvokeDestroy() is an oversight; mFreed is in fact never used outside of the MamaSubscription destructor (where it is set to true) and the MamaSubscriptionImpl constructor (where it is set to false.)  In contrast, MamaBasicSubscription already checks for non-NULL values for mCallback *and* mFreed before calling mCallback->onDestroy().

**Comment by dfedorov-solace** [comment]
Gents, are you taking this patch for 2.4?

**Comment by fquinner** [comment]
I have had a look at this and I'm curious about a few things:

First of all, is the invalid memory access issue something you have actually seen and has this change ever prevented it? It's not clear whether this issue has been observed and whether or not this change fixes it, or if this fix is purely theoretical. If it has been observed, could you provide some replication code please?

Second of all, do you have an implementation for subscription mute in your bridge? Depending on the code displaying problematic behaviour, there is a chance that the callbacks shouldn't be fired in the first place.

I agree that this change is safe to put in, but I want to be sure that it actually fixes an observed problem which can be reproduced in an application and that this fix can be shown to remedy it before putting this in. I also would like to investigate the possibility of fixing this in other ways.

Also just to follow up from a comment from the original email thread:

> I’ve also compared to the Qpid bridge which seems to do an inline onDestroy callback as a part their MiddlewareBridgeMamaSubscription_destroy

That's actually not true - it reads like that if you miss the fact that in MAMA subscription.c, it actually sets cb.onDestroy = mamaSubscriptionImpl_onSubscriptionDestroyed which is an intermediary to hook into the subscription state machine - the onDestroy triggered by the bridge doesn't bubble straight up to the application CB.

And another note from this post:

> Even if a core does not occur, the application would see onDestroy() twice – once inline with when the destroy was started and a second time when the lower layer destroy was completed.

This feels wrong and possibly the root cause of all this heartache. If destroying a subscription was synchronous, there would be no need to run around implementing cleanup code for your application in a callback - you could just do it there and then. At the very least, it should be one _or_ the other - never both.

**Comment by cjwmorgan-sol-sys** [comment]
> First of all, is the invalid memory access issue something you have actually seen and has this change ever prevented it?

Yes we have observed this and this patch prevents the issue. If you would like I could write a unit test with our bridge, if necessary. Since the patch is safe and solves a real issue for our bridge it would be nice to get into 2.4.0.

> Second of all, do you have an implementation for subscription mute in your bridge?

It does and the subscription is mute. Does mute mean there should be no callbacks at all? Or just no onMsg callback?

> That's actually not true - it reads like that if you miss the fact that in MAMA subscription.c, it actually sets cb.onDestroy = mamaSubscriptionImpl_onSubscriptionDestroyed which is an intermediary to hook into the subscription state machine - the onDestroy triggered by the bridge doesn't bubble straight up to the application CB.

True, thanks I took a closer look and by calling the intermediary to hook into the subscription state machine its changes the state for deactivating subscription to deactivated by the bridge subscription Destroy and once it returns up to the mamaSubscription_destroy then invokes the subscription onDestroy callback.

> This feels wrong and possibly the root cause of all this heartache. At the very least, it should be one or the other - never both.

Agreed. The provided patch should allow for this.

**Comment by fquinner** [comment]
OK thanks Chris, considering the time constraints and the safety of the fix, I'll get this into RC3, though I'd like to see the application code that recreates this for the next QA pass. If that's in the form of a unit test, that's even better.

**Comment by fquinner** [comment]
Patch pushed to release branch: 37721ac553f7ed5d078c00dbbe724286ebaf2101
