### ISSUE TITLE
are "wildcard" subscriptions supported w/qpid?

### ISSUE THREAD

**Issue by btorpey** [OpenMAMA/OpenMAMA#266]
# are "wildcard" subscriptions supported w/qpid?
## Summary
qpidBridgeMamaSubscription_createWildCard returns MAMA_STATUS_NOT_IMPLEMENTED

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
Curious if wildcard subscriptions are supported with qpid.  They don't appear to be, but it appears that they could be:  https://qpid.apache.org/releases/qpid-0.32/programming/book/section-addresses.html#idm228614476592

Perhaps there is no difference with qpid?

**Comment by fquinner** [comment]
Note that we use the [qpid proton C API](https://qpid.apache.org/releases/qpid-proton-0.16.0) so not all of the qpid based functionality is actually available in the API that we use, and almost certainly wasn't at the time when this bridge was written (around about version 0.4).

The way the code is structured today, it wouldn't work even if the message reaches the receiver because there is a receive side check which looks for an existing subscription to match each incoming message with so we would need changes to support this even if the wildcards in the URL magically tied all this together. I'm certainly curious as to whether or not the subscription path gets opened up by these wildcards though.

**Comment by fquinner** [comment]
Not currently supported and unlikely to be picked up.
