### ISSUE TITLE
bug in mamaMsg_updateSubMsg?

### ISSUE THREAD

**Issue by bill-torpey-ullink** [OpenMAMA/OpenMAMA#297]
bug in mamaMsg_updateSubMsg?
## Summary
It looks like the current implementation of mamaMsg_updateSubMsg has a bug where it passes the mamaMsg to the payload bridge, rather than the payload. 

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

## Details
The payload function takes a payload object, but `mamaMsg_updateSubMsg` passes in the Mama message -- since both are defined as `void*` there is no compiler checking of these types.

**Comment by fquinner** [comment]
Yes this one is a bit of a pickle. I think the problem here is actually more that the bridge function prototype is in fact wrong, and that MAMA Message *should* be passed to the bridge. The qpid bridge actually has a comment acknowledging this oddity:

https://github.com/OpenMAMA/OpenMAMA/blob/master/mama/c_cpp/src/c/payload/qpidmsg/payload.c#L2374

Unfortunately this doesn't align with what happens in `*Payload_addMsg` which *does* pass in and expect a payload value. I think if anything, that method should change to also accept a mamaMsg as an argument, and we should fix both prototypes to align with this (in MAMA 6.3.0 since this will break the bridge again).

Hear me out here - this seems counter intuitive initially but I think it makes sense:

1. It aligns with the more frequently used `*Payload_addVectorMsg` methods which all pass in MAMA Messages as arguments.
2. It means the underlying bridge *could* transcode payloads from other bridges in a payload agnostic way if it chooses to support that (e.g. you could add a subMsg of type qpid to one of type omnm - consider a caching and distribution application bridging payload types).

**Comment by bill-torpey-ullink** [comment]
If that's the direction you want to go, I have no problem with it (but please let's try to avoid the "death by a thousand cuts" of an API that is constantly in flux).  You know the code *much* better than I do, so if you can think of other similar "adjustments", I would say that now is the time.

I've already submitted a pull request for omnm that works in my environment.  Unfortunately, the Mama unit tests are not helpful -- the updateSubMsg tests are disabled, presumably because they return (spurious?) errors.  

(I'm sure you'll agree that the Mama unit tests could use some serious work -- but I can imagine there's not a line out the door of people wanting to work on them ;-)

I'm assuming that with this change you would also like to change the function declarations to reflect the proper type (not that it matters to the compiler -- don't you just love those void*'s!)

Or let me know and I'll submit a pull request on OpenMAMA as well.

**Comment by cjwmorgan-sol** [comment]
With the release of 6.3.0 wouldn't it be a good time to change the function declarations to the proper type?

**Comment by fquinner** [comment]
https://github.com/OpenMAMA/OpenMAMA/pull/397
