### ISSUE TITLE
mamaSubscription_createBasicWildCard  concatenates source, symbol

### ISSUE THREAD

**Issue by bill-torpey** [OpenMAMA/OpenMAMA#324]
## Summary
When subscribing to a wildcard with both source and symbol, mamaSubscription_createBasicWildCard  passes a concatenation of source and symbol to transport bridge in source and NULL in symbol.

Is this intended behavior, and if so why? 

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [ ] Examples

**Comment by bill-torpey-ullink** [comment]
On a related note, `mamaSubscriptionImpl_completeBasicInitialisation` (subscription.c) appears to swap source and symbol when calling bridge function:

```
3077                 case wc_none:
3078                         ret = impl->mBridgeImpl->bridgeMamaSubscriptionCreate(
3079                             &impl->mSubscBridge,
3080                             impl->mSubscSymbol,
3081                             NULL,
3082                             impl->mTransport,
3083                             impl->mQueue,
3084                             cb,
3085                             impl,
3086                             impl->mClosure);
```

Is this a bug?  Or is this intended behavior?

FWIW, my application makes no use of source.symbol, simply a single topic.  I'd been assuming that should be passed in symbol -- is that correct?

TIA...

**Comment by fquinner** [comment]
There's more.... https://github.com/OpenMAMA/OpenMAMA/blob/master/mama/c_cpp/src/c/dqpublisher.c#L67

I think this is a hangover from what I would call the middleware specific assumption that the delimiter between a source and a topic will always be a dot. It's something that I have seen before when i wanted to use a slash as a delimiter to be more URL-ey:

https://lists.linux-foundation.org/pipermail/openmama-dev/2014-June/001247.html

At the moment, it's most likely going to be a case of letting sleeping dogs lie unless it causes a problem, but this is something that I'd like to get around to standardising on eventually.

Unfortunately some interfaces force collapsing of topics. The `mamaSubscription_createBasicWildCard` function calls `mamaSubscription_createBasic` which doesn't distinguish between topic and source so that granularity gets lost en route.

I would like to get around to fixing this at some point though. Most likely for 6.3.x since bridges which expect the old concat / one sited behaviour may need to adapt.

**Comment by bill-torpey-ullink** [comment]
OK, got it.  So for now, just live with it, but be prepared to make changes when it gets sorted out.

FWIW, the closest thing I've found to a "standard" in this area is: http://docs.oasis-open.org/wsn/2004/06/wsn-WS-Topics-1.2-draft-01.pdf

In general, I guess that Mama doesn't want to be in the business of interpreting topic expressions, preferring to leave that to the bridges.  In our library we convert WS-Topic expressions to the appropriate form for the underlying middleware (dots, regex, etc.).
