### ISSUE TITLE
JNI crash in MamaListen.java when using platformInfo.toString()

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#69]
Replacing [BZ-114] (http://bugs.openmama.org/show_bug.cgi?id=114)

1. Build OpenMama 3.2.x Next branch
2. Modify MamaListen.java to add call to platformInfo.toString() in onConnect() and onAccept() callbacks.
3. Run with Wombat adapter connecting to MamaCache using NSD.
4. Get JNI crash.

It appears that the incorrect pointer level is retrieved in mama/jni/src/c/mamatransportjni.c::mamaTransportImpl_getConnectionObject().

platformInfo is cast to a mamaConnection*, but it is actually a mamaConnection, which is itself a typedef to a mamaConnectionImpl_*. Also the CAST_POINTER_TO_JLONG dereferences the ptr, which is at the incorrect level.

**Comment by fquinner** [comment]
Vela ref: PLAT-398

**Comment by martiqueralt** [comment]
Hey folks,

We do actually have a patch for this one. I will open a Pull Request with the changes on it. 
After investigation, this bug comes actually from a change we made to the WMW bridge ages ago (Vela ref OMAMA-134). We basically didn't update the JNI layer to take this fix into account so that's why it was crashing.

It has been tested patch fixes the issue.

**Comment by fquinner** [comment]
Fix submitted in #209
