### ISSUE TITLE
SCons doesn't have a DESTDIR mechanism

### ISSUE THREAD

**Issue by adriennea** [OpenMAMA/OpenMAMA#77]
Replacing [BZ-89] (http://bugs.openmama.org/show_bug.cgi?id=89)

SCons also doesn't seem to understand DESTDIR. When building a package, the tools set DESTDIR to have the "install" file-set deployed to some temporary tree.  E.g. with autotools, I can do

    ./configure --prefix=/opt/foo
    DESTDIR=/tmp/package make install

and the files would end up in /tmp/package/opt/foo - any content inside
the files that needs to know the prefix would just have "/opt/foo"

Running a command like

    find /tmp/package

then shows everything that will be deploying to a system.

If I use

    scons prefix=/tmp/package/opt/foo

then something in the code may actually think it is going to run from
that location, hence it is really important to have DESTDIR and prefix
defined independently.

From what I've read elsewhere, people using SCons need to manually
implement workarounds for things like SONAME and DESTDIR as SCons
doesn't support them.

**Comment by fquinner** [comment]
Just looking through the backlog here I dont think this is a big deal. It's different if you compile libraries with autoconf, automake and libtool because that absolutely does generate libtool archive files that would need to be edited / deleted if the installer folder moved, but the scons generated libraries are designed to be freely moved so I think this is fine as-is.
